### ISSUE TITLE
Hemonc ETL raises KeyError

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/therapy-normalization#403]
I'm working on automating therapy ETL DDB updates. I am using `thera-py[etl]==0.5.0.dev2` and got this error when running Hemonc. I will be blocked until this is resolved

```
Loading HemOnc...
Downloading 9CY9C6...

0.00B [00:00, ?B/s]
8.00kB [00:01, 4.55kB/s]
64.0kB [00:01, 44.6kB/s]
208kB [00:02, 159kB/s]  
265kB [00:02, 125kB/s]
Transforming and loading data to DB...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/therapy/cli.py", line 275, in <module>
    update_normalizer_db()
  File "/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/therapy/cli.py", line 243, in update_normalizer_db
    _update_normalizer(list(SourceName), db, update_merged, use_existing)
  File "/therapy/cli.py", line 183, in _update_normalizer
    _load_source(n, db, delete_time, processed_ids, use_existing)
  File "/therapy/cli.py", line 107, in _load_source
    processed_ids += source.perform_etl(use_existing)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/therapy/etl/base.py", line 109, in perform_etl
    self._transform_data()
  File "/therapy/etl/hemonc.py", line 200, in _transform_data
    therapies = self._get_rels(therapies, brand_names, conditions)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/therapy/etl/hemonc.py", line 132, in _get_rels
    record["trade_names"].append(brand_names[row[1]])
                                 ~~~~~~~~~~~^^^^^^^^
KeyError: '18918'
```

**Comment by korikuzma** [comment]
@jsstevenson fixed in #404
